services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ant:kfQHL%p&_zR++fNaj7&Â£33Vx-A2|Q
      - MSSQL_PID=Evaluation
    ports:
      - 777:1433
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"
volumes:
  sqlserver_data: